<?php
	//This section contains the configuration details for the database used.
	
	//The database configuration array.
	$database=array();
	
	//The hostname of the MySQL DBMS.
	$database['host']='';
	
	//The database username.
	$database['username']='';
	
	//The password for the database.
	$database['password']='';
	
	//The name of the database to be used. Note that this is not the name of the DBMS.
	$database['name']='';
	
	//A prefix generally used to distinguish the tables used in the database. This is optional.
	$database['prefix']='';
?>