<?php
	//Contains all the social events that occur.
	$events=array(
		array(
			'login'=>'User logged in',
			'logout'=>'User logged out',
			'join'=>'User joined the social network',
			'leave'=>'User left the social network',
			'profile'=>'User updated profile'
		),
		array(
			'friends'=>'User became friends',
			'request'=>'User sent friend request'
		),
		array(
			'post'=>'User posted'
		),
		array(
			'group'=>'User joined group',
			'ungroup'=>'User left group',
			'newgroup'=>'User created group',
			'moderator'=>'User became moderator of group',
			'grpcnf'=>'User accepted member to group',
			'grpreq'=>'User sent group request'
		),
		array(
			'sendmsg'=>'User sent private message',
			'readmsg'=>'User read private message'
		)
	);
?>
